### PR TITLE
Remove uneeded horizontal scroll

### PR DESCRIPTION
**Pull request by kidandcat**
You're awesome!!

### CODE REVIEW

**Comment by egoist** [comment]
maybe you mean `body: {overflow-y: hidden}` because `.homepage: {overflow-y: hidden}` doesn't do anything?

I don't think the horizontal scroll is unnecessary though 😅 especially for mobile devices.

**Comment by kidandcat** [comment]
I tested it with .homepage and worked for me :/

And yes, in general it would be usefull in mobile devices, but your website is responsive and looks perfect on mobile devices, but there should be an element which is growing a little bit more than it should, and that creates a small blank space on the right side of the site, thus making horizontal scroll bar appearing. (which is a little bit ugly, more on desktop)



Anyway, it's your site, you decide :D

**Comment by egoist** [comment]
maybe a screenshot? not sure how to reproduce that 😢

**Comment by kidandcat** [comment]
Windows 10
Version 73.0.3683.86 (Official build) (64 bits)

**Comment by kidandcat** [comment]
Oh, I get the problem now, at least in Chrome, 100vw ignore scrollbars. What happens is that the vertical scrollbar appears, and because you have 100vw, your content is shown behind the scrollbar (for Chrome, that's outside of the screen) and so it enables horizontal scrollbar.

Just changing welcome 100vw to 100% removes the horizontal scrollbar in Chrome.



https://stackoverflow.com/a/33606668/4158710

**Comment by egoist** [comment]
thanks for the fix 😬

**Pull request merged**
